version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/scripts/stop_server
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/scripts/post_deploy.sh
      timeout: 300
      runas: root
